# Generated by Django 4.1.3 on 2022-11-08 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Symbol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('company_description', models.CharField(max_length=100)),
                ('symbol', models.CharField(max_length=10)),
            ],
        ),
    ]
