# Generated by Django 4.1.3 on 2022-11-08 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbols', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='market_values',
            field=models.TextField(default='x', max_length=10000),
            preserve_default=False,
        ),
    ]
