# Generated by Django 4.1.3 on 2022-11-08 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('symbols', '0002_symbol_market_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='symbol',
            name='uid',
            field=models.CharField(default='x', max_length=36),
            preserve_default=False,
        ),
    ]
