# Generated by Django 4.1.3 on 2022-11-25 21:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('symbols', '0003_symbol_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symbol',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='symbol',
            name='uid',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
